//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dialog.rc
//
#define IDD_DIALOG1                     101
#define IDD_NETSET                      101
#define IDD_DIALOG2                     102
#define IDD_CHAT                        102
#define IDC_GET_ALLSESSION              1000
#define IDC_SESSION_LIST                1002
#define IDC_CREATE_SESSION              1003
#define IDC_ENTER_SESSION               1004
#define IDC_EDIT_SESSION                1005
#define IDC_EDIT_PLAYER                 1006
#define IDC_CANCEL                      1007
#define IDC_GET_MY_IP                   1008
#define IDC_START                       1008
#define IDC_EDIT_IP_ADDRESS             1009
#define IDC_NOSESSION                   1010
#define IDC_EDIT1                       1011
#define IDC_EDIT2                       1012
#define IDC_MSG                         1012
#define IDC_SENDTO                      1013
#define IDC_MSG_LIST                    1014
#define IDC_LIST_PLAYER                 1015
#define IDC_GAME_START                  1016
#define IDC_HOST_PLAYER                 1017
#define IDC_ONE_PLAY                    1018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
